# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ojyks-server

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build site assets
      working-directory: ${{ github.workspace }}
      run: ls -la

    - name: npm install, build, and test
      working-directory: server
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'ojyks-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8d1607f2d93b451b982085b1e3476471 }}
        package: .
        publish_dir: ./server
